DWAPlannerROS:

  acc_lim_th: 4.2
  acc_lim_x: 3.2


  max_vel_x: 1
  min_vel_x: -1

  max_vel_trans: 1
  min_vel_trans: 1

  max_rot_vel: 0.1
  min_rot_vel: -0.1

  sim_time: 1.5
  #sim_granularity: 0.025
  vx_samples: 15
  vy_samples: 8
  vtheta_samples: 70

  goal_distance_bias: 15.0
  path_distance_bias: 32.0
  occdist_scale: 0.05

  stop_time_buffer: 0.2
  oscillation_reset_dist: 0.05

  forward_point_distance: 0.4

  scaling_speed: 0.25
  #max_scaling_factor: 0.5

  #sim_period: 0.1

  xy_goal_tolerance: 0.015 #meter
  yaw_goal_tolerance: 0.2 #radians
  latch_xy_goal_tolerance: false
  #prune_plan: true

  #rot_stopped_vel: 0.01
  #trans_stopped_vel: 0.01